version: "3.3"

services:
  web:
    container_name: catto_flask
    restart: unless-stopped
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    env_file:
      - .env

volumes:
  postgres_data: 