version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    env_file:
      - /.env
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    env_file:
    - .env